services:
  - type: web
    name: api-catalogos-carros
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn run:app --bind 0.0.0.0:10000 --workers 4
    envVars:
      - key: MONGO_URI
        sync: false
      - key: JWT_SECRET_KEY
        sync: false
      - key: PORT
        value: 10000
    healthCheckPath: /